### ISSUE TITLE
Flattening.cpp undefined reference to `llvm::createLowerSwitchPass()`

### ISSUE THREAD

**Issue by Cryptiiiic** [Qrilee/llvm-obfuscator#2]
`[ 54%] Linking CXX shared library ../../lib/libLTO.so
cd /home/xd/build/tools/lto && /usr/bin/cmake -E cmake_link_script CMakeFiles/LTO.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC  -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -ffunction-sections -fdata-sections -O3 -DNDEBUG  -Wl,-rpath-link,/home/xd/build/./lib  -Wl,-O3 -Wl,--gc-sections  -Wl,--version-script,/home/xd/build/tools/lto/LTO.exports  -Wl,-z,defs -shared -Wl,-soname,libLTO.so.5 -o ../../lib/libLTO.so.5.0.0 CMakeFiles/LTO.dir/LTODisassembler.cpp.o CMakeFiles/LTO.dir/lto.cpp.o -Wl,-rpath,"\$ORIGIN/../lib" ../../lib/libLLVMX86CodeGen.a ../../lib/libLLVMX86AsmPrinter.a ../../lib/libLLVMX86AsmParser.a ../../lib/libLLVMX86Desc.a ../../lib/libLLVMX86Info.a ../../lib/libLLVMX86Disassembler.a ../../lib/libLLVMX86Info.a ../../lib/libLLVMX86Utils.a ../../lib/libLLVMBitReader.a ../../lib/libLLVMCore.a ../../lib/libLLVMLTO.a ../../lib/libLLVMMC.a ../../lib/libLLVMMCDisassembler.a ../../lib/libLLVMSupport.a ../../lib/libLLVMTarget.a ../../lib/libLLVMAsmPrinter.a ../../lib/libLLVMDebugInfoCodeView.a ../../lib/libLLVMDebugInfoMSF.a ../../lib/libLLVMGlobalISel.a ../../lib/libLLVMSelectionDAG.a ../../lib/libLLVMX86AsmPrinter.a ../../lib/libLLVMX86Utils.a ../../lib/libLLVMObjCARCOpts.a ../../lib/libLLVMPasses.a ../../lib/libLLVMCodeGen.a ../../lib/libLLVMTarget.a ../../lib/libLLVMipo.a ../../lib/libLLVMBitWriter.a ../../lib/libLLVMLinker.a ../../lib/libLLVMScalarOpts.a ../../lib/libLLVMInstCombine.a ../../lib/libLLVMInstrumentation.a ../../lib/libLLVMVectorize.a ../../lib/libLLVMTransformUtils.a ../../lib/libLLVMAnalysis.a ../../lib/libLLVMObject.a ../../lib/libLLVMMCParser.a ../../lib/libLLVMMC.a ../../lib/libLLVMProfileData.a ../../lib/libLLVMIRReader.a ../../lib/libLLVMBitReader.a ../../lib/libLLVMAsmParser.a ../../lib/libLLVMCore.a ../../lib/libLLVMBinaryFormat.a ../../lib/libLLVMSupport.a -lrt -ldl -ltinfo -lpthread -lz -lm ../../lib/libLLVMDemangle.a ../../lib/libLLVMObfuscation.a 
../../lib/libLLVMObfuscation.a(Flattening.cpp.o): In function `(anonymous namespace)::Flattening::runOnFunction(llvm::Function&)':
Flattening.cpp:(.text._ZN12_GLOBAL__N_110Flattening13runOnFunctionERN4llvm8FunctionE+0xf1): undefined reference to `llvm::createLowerSwitchPass()'
collect2: error: ld returned 1 exit status
tools/lto/CMakeFiles/LTO.dir/build.make:167: recipe for target 'lib/libLTO.so.5.0.0' failed
make[2]: *** [lib/libLTO.so.5.0.0] Error 1
make[2]: Leaving directory '/home/xd/build'
CMakeFiles/Makefile2:6973: recipe for target 'tools/lto/CMakeFiles/LTO.dir/all' failed
make[1]: *** [tools/lto/CMakeFiles/LTO.dir/all] Error 2
make[1]: Leaving directory '/home/xd/build'
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2`

This happens when compiling for kali linux chroot environment and on a ubuntu server.

**Comment by Cryptiiiic** [comment]
@Qrilee

**Comment by Qrilee** [comment]
I have not tested compiled ollvm on a linux system ,

**Comment by Qrilee** [comment]
@Cryptiiiic see readme
